# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(570, 390)
        self.labelImie = QtWidgets.QLabel(parent=Dialog)
        self.labelImie.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.labelImie.setObjectName("labelImie")
        self.labelNazwisko = QtWidgets.QLabel(parent=Dialog)
        self.labelNazwisko.setGeometry(QtCore.QRect(10, 50, 61, 31))
        self.labelNazwisko.setObjectName("labelNazwisko")
        self.odpImie = QtWidgets.QLineEdit(parent=Dialog)
        self.odpImie.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.odpImie.setObjectName("odpImie")
        self.odpNazwisko = QtWidgets.QLineEdit(parent=Dialog)
        self.odpNazwisko.setGeometry(QtCore.QRect(70, 60, 113, 20))
        self.odpNazwisko.setObjectName("odpNazwisko")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(230, 10, 151, 80))
        self.groupBox.setObjectName("groupBox")
        self.internista = QtWidgets.QRadioButton(parent=self.groupBox)
        self.internista.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.internista.setChecked(True)
        self.internista.setObjectName("internista")
        self.pediatra = QtWidgets.QRadioButton(parent=self.groupBox)
        self.pediatra.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.pediatra.setObjectName("pediatra")
        self.dermatolog = QtWidgets.QRadioButton(parent=self.groupBox)
        self.dermatolog.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.dermatolog.setObjectName("dermatolog")
        self.czyprywatna = QtWidgets.QCheckBox(parent=Dialog)
        self.czyprywatna.setEnabled(True)
        self.czyprywatna.setGeometry(QtCore.QRect(420, 50, 111, 16))
        self.czyprywatna.setChecked(True)
        self.czyprywatna.setObjectName("czyprywatna")
        self.rezerwoj = QtWidgets.QPushButton(parent=Dialog)
        self.rezerwoj.setGeometry(QtCore.QRect(240, 120, 81, 41))
        self.rezerwoj.setObjectName("rezerwoj")
        self.wynikrezerwacji = QtWidgets.QLabel(parent=Dialog)
        self.wynikrezerwacji.setGeometry(QtCore.QRect(10, 180, 551, 191))
        self.wynikrezerwacji.setText("")
        self.wynikrezerwacji.setObjectName("wynikrezerwacji")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelImie.setText(_translate("Dialog", "Imie"))
        self.labelNazwisko.setText(_translate("Dialog", "Nazwisko"))
        self.groupBox.setTitle(_translate("Dialog", "Specjalizacja lekarska"))
        self.internista.setText(_translate("Dialog", "Internista"))
        self.pediatra.setText(_translate("Dialog", "Pediatra"))
        self.dermatolog.setText(_translate("Dialog", "Dermatolog"))
        self.czyprywatna.setText(_translate("Dialog", "Czy Wizyta prywatna?"))
        self.rezerwoj.setText(_translate("Dialog", "Rezerwój"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
